name: wemeet
description: "TizenOS-flutter version"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # --- TizenOS-flutter, WerableOS 공용 패키지(modern.yaml에 복붙해야함) ---


  # --- TizenOS-flutter 호환 패키지 ---
  health: ^13.1.3 # Dart 3.2.x와 호환되는 버전

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0