name: Docker 이미지 빌드 및 푸시

# 1. 언제 실행할지 (트리거)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '.devcontainer/Dockerfile' 
      - '.devcontainer/devcontainer.json'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      # 1. GitHub 레포지토리 코드를 가상 머신으로 복사
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # context: .
          #   프로젝트 루트 폴더를 빌드 컨텍스트로 사용
          context: .
          
          # file: .devcontainer/Dockerfile
          #   빌드할 Dockerfile의 경로
          file: .devcontainer/Dockerfile

          # push: true
          #   빌드 완료 후 Docker Hub로 푸시
          push: true

          # tags: rlawodms364/we-meet:3.0.0
          #   푸시할 이미지 태그. (devcontainer.json의 태그와 일치시켜야 함)
          #   [팁] 아래처럼 2개를 쓰면 '3.0.0'과 'latest' 태그 둘 다 업데이트됩니다.
          tags: |
            rlawodms364/we-meet:3.0.1
            rlawodms364/we-meet:latest